In [1]:
#import libaries

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix

In [3]:
##load the data

In [4]:
data = pd.read_csv("datasets/BreastC_Data.csv")

In [5]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [6]:
X = data.iloc[:,1:-1].values
y = data.iloc[:,-1].values

In [10]:
#train test split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [12]:
X_train.shape,X_test.shape

((546, 9), (137, 9))

In [13]:
## feature scaling

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## train the logistic regression

In [17]:
lreg = LogisticRegression()
lreg.fit(X_train,y_train)

LogisticRegression()

In [20]:
#predicting the test data using logistic regression

In [21]:
y_pred_logreg = lreg.predict(X_test)

In [30]:
#making the confusion matrix & printing the accuracy score

In [24]:
cm = confusion_matrix(y_test,y_pred_logreg)
print(cm)
print(accuracy_score(y_test,y_pred_logreg))

[[89  2]
 [ 3 43]]
0.9635036496350365


## Train the KNN

In [25]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [26]:
#predicting the test data using knn

In [27]:
y_pred_knn = knn.predict(X_test)

In [29]:
#making the confusion matrix & printing the accuracy score

In [31]:
cm = confusion_matrix(y_test,y_pred_knn)
print(cm)
print(accuracy_score(y_test,y_pred_knn))

[[89  2]
 [ 1 45]]
0.9781021897810219


## Train the linear SVC

In [32]:
svc_lin = SVC(kernel='linear',random_state=42)
svc_lin.fit(X_train,y_train)

SVC(kernel='linear', random_state=42)

In [33]:
#predicting the test data using linear svc

In [34]:
y_pred_lin_svc = svc_lin.predict(X_test)

In [35]:
#making the confusion matrix & printing the accuracy score

In [36]:
cm = confusion_matrix(y_test,y_pred_lin_svc)
print(cm)
print(accuracy_score(y_test,y_pred_lin_svc))

[[88  3]
 [ 2 44]]
0.9635036496350365


## Train the Kernel SVC

In [38]:
svc_non_lin = SVC(kernel='rbf',random_state=42)
svc_non_lin.fit(X_train,y_train)

SVC(random_state=42)

In [39]:
#predicting the test data using non linear svc

In [40]:
y_pred_non_lin_svc = svc_non_lin.predict(X_test)

In [41]:
#making the confusion matrix & printing the accuracy score

In [42]:
cm = confusion_matrix(y_test,y_pred_non_lin_svc)
print(cm)
print(accuracy_score(y_test,y_pred_non_lin_svc))

[[87  4]
 [ 2 44]]
0.9562043795620438


## Train the Gaussian Naive Bayes

In [43]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB()

In [44]:
#predicting the test data using Naive Bayes

In [45]:
y_pred_nb = gnb.predict(X_test)

In [46]:
#making the confusion matrix & printing the accuracy score

In [47]:
cm = confusion_matrix(y_test,y_pred_nb)
print(cm)
print(accuracy_score(y_test,y_pred_nb))

[[86  5]
 [ 1 45]]
0.9562043795620438


## Train Decison Tree Classifier

In [49]:
dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [50]:
#predicting the test data using DTC

In [51]:
y_pred_dtc = dtc.predict(X_test)

In [52]:
#making the confusion matrix & printing the accuracy score

In [53]:
cm = confusion_matrix(y_test,y_pred_dtc)
print(cm)
print(accuracy_score(y_test,y_pred_dtc))

[[88  3]
 [ 2 44]]
0.9635036496350365


## Train Random Forest Classifier

In [55]:
rfc = RandomForestClassifier(n_estimators=50,random_state=42,criterion='entropy')
rfc.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=50, random_state=42)

In [56]:
#predicting the test data using RFC

In [57]:
y_pred_rfc = rfc.predict(X_test)

In [58]:
#making the confusion matrix & printing the accuracy score

In [59]:
cm = confusion_matrix(y_test,y_pred_rfc)
print(cm)
print(accuracy_score(y_test,y_pred_rfc))

[[88  3]
 [ 4 42]]
0.948905109489051
