In [64]:
#import libraries

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [66]:
#read the data

In [67]:
data = pd.read_csv("datasets/Data.csv")
data.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [68]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [69]:
## split the data

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [71]:
#train the linear model

In [72]:
lreg = LinearRegression()
lreg.fit(X_train,y_train)

LinearRegression()

In [73]:
##predict the unseen data

In [74]:
y_pred = lreg.predict(X_test)

In [75]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1 ))

[[455.68 455.27]
 [438.73 436.31]
 [434.16 440.68]
 ...
 [482.17 479.53]
 [435.42 435.76]
 [458.76 457.1 ]]


In [76]:
## model evaluation

In [77]:
r2_score(y_test,y_pred)

0.9301046431962188

In [78]:
## polynomial regression

In [79]:
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression()

In [80]:
##predict the unseen data

In [81]:
y_pred_poly = regressor.predict(poly_reg.fit_transform(X_test))

In [82]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_poly.reshape(len(y_pred_poly),1), y_test.reshape(len(y_test),1)), 1 ))

[[455.91 455.27]
 [437.66 436.31]
 [434.51 440.68]
 ...
 [482.63 479.53]
 [435.28 435.76]
 [460.01 457.1 ]]


In [83]:
## model evaluation

In [84]:
r2_score(y_test,y_pred_poly)

0.9431898789519529

In [85]:
## SVR 

In [86]:
##feature scaling

In [87]:
y_copy = y.reshape(len(y),1)

In [88]:
X_train, X_test, y_train, y_test = train_test_split(X,y_copy,test_size=0.2,random_state=42)

In [89]:
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [90]:
## training svr

In [91]:
svr_reg = SVR(kernel = 'rbf')
svr_reg.fit(X_train_sc, y_train_sc)

C:\Users\SKUP\AppData\Local\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [92]:
## predicting the unseen data

In [93]:
np.set_printoptions(precision=2)
y_pred_svr = sc_y.inverse_transform(svr_reg.predict(sc_X.transform(X_test)).reshape(-1,1))
print(np.concatenate((y_pred_svr.reshape(len(y_pred_svr),1), y_test.reshape(len(y_test),1)),1))

[[456.77 455.27]
 [437.12 436.31]
 [434.62 440.68]
 ...
 [483.15 479.53]
 [435.35 435.76]
 [458.56 457.1 ]]


In [94]:
## model evaluation

In [95]:
r2_score(y_test,y_pred_svr)

0.9468468206093839

In [52]:
## decision tree regressor

In [98]:
dataset = pd.read_csv('datasets/Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [100]:
dtreg = DecisionTreeRegressor(random_state = 0)
dtreg.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [54]:
#predict on unseen data

In [101]:
y_pred_dt = dtreg.predict(X_test)

In [102]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_dt.reshape(len(y_pred_dt),1), y_test.reshape(len(y_test),1)), 1 ))

[[431.28 431.23]
 [459.59 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.74 463.28]]


In [103]:
#evaluate the model

In [104]:
r2_score(y_test,y_pred_dt)

0.922905874177941

In [105]:
## random forest regressor

In [106]:
rfreg = RandomForestRegressor(n_estimators=100,random_state = 0)
rfreg.fit(X_train, y_train)

RandomForestRegressor(random_state=0)

In [107]:
## predict the unseen data

In [108]:
y_pred_rf = rfreg.predict(X_test)

In [109]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_rf.reshape(len(y_pred_rf),1), y_test.reshape(len(y_test),1)), 1 ))

[[433.64 431.23]
 [457.71 460.01]
 [463.41 461.14]
 ...
 [468.97 473.26]
 [439.18 438.  ]
 [461.29 463.28]]


In [110]:
#model evaluation

In [111]:
r2_score(y_test,y_pred_rf)s

0.9651050302169809