In [1]:
#import standard libraries

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score

In [4]:
#import the data

In [5]:
data = pd.read_csv("datasets/Social_Network_Ads.csv")

In [6]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [7]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [9]:
## train test split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
## scaling the data

In [12]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
X_train[:3],X_test[:3]

(array([[-1.06675246, -0.38634438],
        [ 0.79753468, -1.22993871],
        [ 0.11069205,  1.853544  ]]),
 array([[ 0.79753468, -1.40447546],
        [ 2.07309956,  0.51542886],
        [-0.96863208, -0.76450736]]))

In [15]:
## training the logistic regression

In [23]:
logreg = LogisticRegression(random_state=42)
logreg.fit(X_train,y_train)

LogisticRegression(random_state=42)

In [26]:
## predict on new data

In [27]:
logreg.predict(sc.transform([[56,2100000]]))

array([1], dtype=int64)

In [17]:
##predicting the new data

In [24]:
y_pred = logreg.predict(X_test)

In [28]:
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1 )

array([[0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 1],
       [1,

In [21]:
## create confusion matrix

In [25]:
confusion_matrix(y_test,y_pred)

array([[50,  2],
       [ 9, 19]], dtype=int64)

In [31]:
#check  the accuracy score

In [32]:
accuracy_score(y_test,y_pred)

0.8625